name: Deploy to firebase

on:
  push:
    branches: 
      - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout to master
      uses: actions/checkout@master
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: techathon-8733a
